[build]
  publish = "/"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
